### ISSUE TITLE
sqmod.ini log Filename doesn't support strftime.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#1]
This works perfectly: Filename=script.log, but if a strfttime is used as the name of the log file, it doesn't create that log file: Filename=script_%F.log

**Comment by iSLC** [comment]
Turns out that the `%F` format specifier is not supported by the compiler. Being a specifier from the `C99` standard. Some compilers haven't fully implemented all the new format specifiers.

To get around this minor and probably temporary limitation you could use the `C90` standard and combine `%Y-%m-%d` to obtain the same result since `%F` is just a shortcut for that.

So you should have: `Filename=script_%Y-%m-%d.log`

This should achieve the same result while still being compatible with most compilers.
