### ISSUE TITLE
SqVehicle.Fix doesn't exist.

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#20]
Input:
`SqVehicle.Fix();`

Output:
`[ERR] the index 'Fix' does not exist`

**Comment by iSLC** [comment]
The function is there and registered https://github.com/iSLC/VCMP-SqMod/blob/master/source/Entity/Vehicle.cpp#L1747

It works on my end:

```
function onPlayerSpawn(player)
{
    local vehicle = SqVehicle.CreateEx(145, player.World, player.PosX - 5.0, player.PosY + 5.0, player.PosZ, 0, 0, 0);

    printf(vehicle); // 1

    vehicle.Fix();

    printf("vehicle fixed");
}

SqCore.Bind(SqEvent.PlayerSpawn, this, onPlayerSpawn);
```

Output:

```
[SCS] The Squirrel plugin was loaded successfully
Player 'XYZ' ID 0 connected.
[USR] 1
[USR] vehicle fixed
```

Try to recompile the module. Also, make sure that the server isn't running otherwise it'll fail to copy the executable in the plugins folder and replace the old one.
