### ISSUE TITLE
SqCore.SetState sometimes doesn't affect

### ISSUE THREAD

**Issue by rasikhq** [VCMP-SqMod/SqMod#34]
SqCore.SetState( 0 );

This is supposed to stop the event from moving downwards

local PlayerBanned = player.IsBanned();
if( PlayerBanned ) {
	player.Kick();
	SqCore.SetState( 0 );
	return true;
}

Even with this code it SOMETIMES goes without cancelling.

**Comment by iSLC** [comment]
`SqCore.SetState(0);` is just a random integer value that you can set to whatever you want. It was meant to be used as a communication mechanism between different signals emitted by the server. Since you cant return a value from there. Because you can have multiple listeners to a single event.

For example, if you're in the middle of a signal and you encounter an error, then you can set a specific error code in there and check for that error code when the signal finished emission to all connected slots.

In a few cases the plugin uses that value to report back an issue. Something like an error code returned by the server or to return back to the server in some events/callbacks than need an answer.  For example https://github.com/iSLC/VCMP-SqMod/blob/master/source/Main.cpp#L362

If you want to cancel, just throw an exception. Heck, `throw null;`. Right now, the plugin does not allow someone to stop the execution of a signal from the plugin. It simply ignores returned values. So, returning false or true has no effect. I could look into changing this behavior if necessary.
