### ISSUE TITLE
Number of building threads is hardcoded in Makefile

### ISSUE THREAD

**Issue by dracc** [VCMP-SqMod/SqMod#44]
I fail to see a good answer to the question "why?".
Default is 1, advanced users probably know about the `-j` switch anyways.

**Comment by iSLC** [comment]
IIRC, when I created the make script, changing the number of threads had no effect. Besides, the make script was only for headless builds. Which don't happen quite often.

Because debugging from make output is a pain in the a$$. Which is why neither I nor anyone else don't use it much.

I'm using CMake for my personal projects and I had planned to create a CMake script at some point. But that moment never came due to my lack of interest in the mod.

If you have a suggestion that you can implement then have at it and feel free to make a pull request.

**Comment by iSLC** [comment]
This has been addressed after an overall restructure of the project. Which comes with a new build system based on CMake. PR https://github.com/iSLC/VCMP-SqMod/pull/47

I am closing this assuming the request has been fulfilled. Let me know otherwise.
