### ISSUE TITLE
Addition of a command system for the IRC module

### ISSUE THREAD

**Issue by Drake486** [VCMP-SqMod/SqMod#6]
Just like the main module gives us the option to create commands internally, the same for the IRC would be good as well.

**Comment by Drake486** [comment]
Why is this closed?

**Comment by iSLC** [comment]
Because the same command system used for the game can be used for IRC in a non intrusive way. There's no point in writing a separate command system for IRC since the main one from the host plugin can be shared. Basically, create a different command manager dedicated for IRC commands and start adding commands to it. Should work out of the box.
